image: node:latest

variables:
  NPM_TOKEN: d2c50f53-60ea-4553-9c63-2692bebef988

cache:
  paths:
    - node_modules/

test:
  stage: build
  script:
    - touch .npmrc
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm install --loglevel=warn --spin=false
    - npm test -- --coverage-report=text-summary
